/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.menu_profil;

import java.awt.MenuItem;
import java.awt.event.ActionListener;
import javax.swing.Icon;

/**
 *
 * @author USER
 */
public class menu_item extends javax.swing.JPanel {

    /**
     * Creates new form menu_item
     */
    public Menu_profil(Icon icon, boolean, sbm, Icon iconSub, String menu_item, ActionListener act, MenuItem... subMenu) {
        initComponents();
        
        lb_icon.setIcon(icon);
        lb_menu_item.setText(menuName);
        lb_iconsub.setIcon(iconSub);
        lb_iconsub.setVisible(sbm);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_name = new javax.swing.JLabel();
        lb_icon = new javax.swing.JLabel();
        lb_iconsub = new javax.swing.JLabel();

        menu_name.setText("Menu_item");

        lb_icon.setText("jLabel2");

        lb_iconsub.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lb_iconsub)
                .addGap(18, 18, 18)
                .addComponent(lb_icon)
                .addGap(26, 26, 26)
                .addComponent(menu_name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_name, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lb_icon)
                    .addComponent(lb_iconsub))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_iconsub;
    private javax.swing.JLabel menu_name;
    // End of variables declaration//GEN-END:variables
}
